# Generated by Django 5.1.3 on 2024-11-28 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalogue", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=48)),
                ("description", models.TextField(blank=True)),
                ("is_recommended", models.BooleanField(default=True)),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("updated_time", models.DateTimeField(auto_now=True)),
                (
                    "rating",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "Bad"),
                            (2, "Not Bad"),
                            (3, "OK"),
                            (4, "Good"),
                            (5, "Very Good"),
                        ],
                        default=5,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="catalogue.product",
                    ),
                ),
            ],
        ),
    ]
