# Generated by Django 5.0.7 on 2024-09-14 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transaction", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionArchive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.SmallIntegerField(
                choices=[
                    (1, "Charge"),
                    (2, "Purchase"),
                    (3, "Transfer receiver"),
                    (4, "Transfer sender"),
                ],
                default=1,
            ),
        ),
        migrations.CreateModel(
            name="TransferTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                (
                    "received_transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="received_archive",
                        to="transaction.transaction",
                    ),
                ),
                (
                    "sent_transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sent_transfer",
                        to="transaction.transaction",
                    ),
                ),
            ],
        ),
    ]
