# Generated by Django 5.0.7 on 2024-10-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transaction", "0002_transactionarchive_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "permissions": [("has_score_permission", "Has Score Permission")],
            },
        ),
    ]
