# Generated by Django 5.0.7 on 2024-11-17 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0006_productvariant"),
    ]

    operations = [
        migrations.AddField(
            model_name="productattribute",
            name="options",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="productattribute",
            name="attribute_type",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "integer"), (2, "string"), (3, "float"), (4, "list")],
                default=1,
            ),
        ),
        migrations.DeleteModel(
            name="ProductVariant",
        ),
    ]
