# Generated by Django 5.1.3 on 2024-12-05 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0001_initial"),
        ("catalogue", "0002_size_productsize"),
    ]

    operations = [
        migrations.AddField(
            model_name="basketline",
            name="color",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalogue.productcolor",
            ),
        ),
        migrations.AddField(
            model_name="basketline",
            name="size",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalogue.productsize",
            ),
        ),
    ]
